### PR TITLE
move readme to markdown

### PR DESCRIPTION
**Pull request by c-cube**
first attempt, at least it looks better as a landing page

### CODE REVIEW

**Comment by rizo** [comment]
Converted summary items into links, hope you don't mind :)

**Comment by pmetzger** [comment]
@loxs so it looks like it's getting done already.

**Comment by pmetzger** [comment]
I suggest merging this and then doing another round of cleanups. Any objections?

**Comment by loxs** [comment]
Cool, when CI passes, we can merge this. Anyone who has commit access, please do it, as I won't be around for the next few hours.

**Pull request merged**
